// frontend/src/dummyData.js

export const dummyJobs = [
  {
    id: 9001,
    title: "Senior P&C Pricing Actuary (Sample)",
    company: "Global Assurance Inc.",
    location: "🇺🇸 USA |",
    job_type: "Full-time",
    posting_date: "2024-08-16",
    tags: "Pricing, P&C, Risk, Modelling, Python",
  },
  {
    id: 9002,
    title: "Actuarial Consultant - Pensions (Sample)",
    company: "Strategic Retirement Partners",
    location: "🇬🇧 UK|",
    job_type: "Full-time",
    posting_date: "2024-08-13",
    tags: "Consulting, Pensions, Life, Reporting",
  },
  {
    id: 9003,
    title: "Predictive Modeling Intern (Sample)",
    company: "DataDriven Decisions",
    location: "🇺🇸 USA |",
    job_type: "Internship",
    posting_date: "2024-08-11",
    tags: "Intern, Modelling, Data Science, R, SQL",
  },
  {
    id: 9004,
    title: "Life Insurance Reserving Analyst (Sample)",
    company: "SecureRe",
    location: "🇨🇦 Canada |",
    job_type: "Full-time",
    posting_date: "2024-08-11",
    tags: "Reserving, Reporting, IFRS17, Life",
  },
  {
    id: 9005,
    title: "Head of Actuarial Function (Sample)",
    company: "Apex Insurers Europe",
    location: "🇩🇪 Germany |",
    job_type: "Full-time",
    posting_date: "2024-08-04",
    tags: "Leadership, Risk, Solvency II, Health",
  },
  {
    id: 9006,
    title: "Health Actuarial Analyst (Sample)",
    company: "Wellness Health Group",
    location: "🇺🇸 USA |",
    job_type: "Full-time",
    posting_date: "2024-08-18",
    tags: "Health, Pricing, SQL, Excel, Valuation",
  },
  {
    id: 9007,
    title: "Reinsurance Actuary - Associate (Sample)",
    company: "Bermuda Re",
    location: "🇧🇲 Bermuda |",
    job_type: "Full-time",
    posting_date: "2024-08-17",
    tags: "Reinsurance, P&C, Capital, Associate",
  },
  {
    id: 9008,
    title: "Entry-Level Actuarial Student",
    company: "Future Forward Financial",
    location: "🇺🇸 USA |",
    job_type: "Full-time",
    posting_date: "2024-08-18",
    tags: "Entry-Level, Student, Life, Excel",
  },
  {
    id: 9009,
    title: "Actuarial Systems  Lead",
    company: "Tech Solutions ",
    location: "🇮🇳 India | 🏠 Remote",
    job_type: "Contract",
    posting_date: "2024-08-14",
    tags: "Systems, Python, SQL, Cloud, Contract",
  },
  {
    id: 9010,
    title: "Senior Investment Actuary (Sample)",
    company: "Growth Management",
    location: "🇬🇧 UK |",
    job_type: "Full-time",
    posting_date: "2024-08-08",
    tags: "Investments, ALM, Capital, Modelling",
  },
  
];